# Generated by Django 5.0.6 on 2024-06-20 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_remove_message_room_remove_message_sender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='ChatSession',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
